const OBSERVER_TASKS = "OBSERVER_TASKS";
const CREATE_TASK = "CREATE_TASK";
const DELETE_TASK = "DELETE_TASK";
const DONE_TASK = "DONE_TASK";
const UPDATE_TASK = "UPDATE_TASK";
const SAVE_DATA_FROM_REDUX ="SAVE_DATA_FROM_REDUX";

const todoActionType = {
  OBSERVER_TASKS,
  CREATE_TASK,
  DELETE_TASK,
  DONE_TASK,
  UPDATE_TASK,
  SAVE_DATA_FROM_REDUX
};

export default todoActionType;
