const CREATE_TASK = "CREATE_TASK";
const DELETE_TASK = "DELETE_TASK";
const UPDATE_TASK = "UPDATE_TASK";
const SAVE_DATA_FROM_REDUX ="SAVE_DATA_FROM_REDUX";

const todoActionType = {
  CREATE_TASK,
  DELETE_TASK,
  UPDATE_TASK,
  SAVE_DATA_FROM_REDUX
};

export default todoActionType;
