const OBSERVER_TASKS = "OBSERVER_TASKS";
const CREATE_TASK = "CREATE_TASK";
const DELETE_ALL_TASKS = "DELETE_ALL_TASKS";
const DELETE_TASK = "DELETE_TASK";
const DONE_TASK = "DONE_TASK";
const UPDATE_TASK = "UPDATE_TASK";

const todoActionType = {
  OBSERVER_TASKS,
  CREATE_TASK,
  DELETE_ALL_TASKS,
  DELETE_TASK,
  DONE_TASK,
  UPDATE_TASK
};

export default todoActionType;
